on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to the issue tracker! Before you submit a new issue, please make sure to search for existing ones to avoid duplicates. 
        Provide a clear and detailed description of the problem you're experiencing, including steps to reproduce it."
        pr-message: "Thank you for contributing! Before you create a pull request, ensure that your code follows the project's coding standards. 
        Include a brief summary of the changes and any related issues. If you're unsure about anything, feel free to ask for help in the comments."

  greeting-windows:
    runs-on: windows-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to the issue tracker for Windows! Before you submit a new issue, please make sure to search for existing ones to avoid duplicates. 
        Provide a clear and detailed description of the problem you're experiencing, including steps to reproduce it."
        pr-message: "Thank you for contributing to Windows! Before you create a pull request, ensure that your code follows the project's coding standards. 
        Include a brief summary of the changes and any related issues. If you're unsure about anything, feel free to ask for help in the comments."

  greeting-ios:
    runs-on: macos-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to the issue tracker for iOS! Before you submit a new issue, please make sure to search for existing ones to avoid duplicates. 
        Provide a clear and detailed description of the problem you're experiencing, including steps to reproduce it."
        pr-message: "Thank you for contributing to iOS! Before you create a pull request, ensure that your code follows the project's coding standards. 
        Include a brief summary of the changes and any related issues. If you're unsure about anything, feel free to ask for help in the comments."
